version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: development
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - XDEBUG_ENABLED=${XDEBUG_ENABLED:-true}
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
      - vendor:/var/www/vendor
      - node_modules:/var/www/node_modules
    env_file:
      - .env.local
    networks:
      - app-network
    ports:
      - "9000:9000"
    depends_on:
      maindb:
        condition: service_healthy
      logdb:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    ports:
      - "80:80"
    depends_on:
      - app

  vite:
    build:
      context: .
      dockerfile: ./docker/development/vite/Dockerfile
    restart: unless-stopped
    volumes:
      - .:/var/www
      - node_modules:/var/www/node_modules
    networks:
      - app-network
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

  maindb:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_DATABASE:-app_local}
      - POSTGRES_USER=${DB_USERNAME:-app}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secret}
    volumes:
      - maindb-local-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-app}"]
      interval: 10s

  logdb:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${LOG_DB_DATABASE:-app_logs_local}
      - POSTGRES_USER=${LOG_DB_USERNAME:-app}
      - POSTGRES_PASSWORD=${LOG_DB_PASSWORD:-secret}
    volumes:
      - logdb-local-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${LOG_DB_USERNAME:-app}"]
      interval: 10s

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-local-data:/data
    networks:
      - app-network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s

  horizon:
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: development
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    restart: unless-stopped
    volumes:
      - .:/var/www
      - vendor:/var/www/vendor
    env_file:
      - .env.local
    command: ["watch-horizon.sh"]
    networks:
      - app-network
    depends_on:
      maindb:
        condition: service_healthy
      logdb:
        condition: service_healthy
      redis:
        condition: service_healthy

networks:
  app-network:
    driver: bridge

volumes:
  maindb-local-data:
  logdb-local-data:
  redis-local-data:
  vendor:
  node_modules:
